# -*- coding: utf-8 -*-
"""Modelo E-R «Cuenta y acceso», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion cuenta"""

ENTITIES = {'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Sesion': {'x': 1015, 'y': -315, 'w': 290, 'h': 110, 'kind': 'strong'},
 'CodigoVerificacion': {'x': 1015, 'y': 385, 'w': 340, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_Sesion_Usuario',
  'label': 'Abre',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('Sesion', 'N', '1', True, False, None)],
  'x': 508,
  'y': -158},
 {'id': 'FK_CodigoVerificacion_Usuario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('CodigoVerificacion', 'N', '1', True, False, None)],
  'x': 508,
  'y': 192}]

ATTRS = [{'id': 'Usuario.id_usuario', 'label': 'id_usuario', 'x': 404, 'y': 327, 'kind': 'key', 'owner': 'Usuario'},
 {'id': 'Usuario.tipo_cuenta',
  'label': 'tipo_cuenta',
  'x': 418,
  'y': 498,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.estado_cuenta',
  'label': 'estado_cuenta',
  'x': 220,
  'y': 471,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.rol', 'label': 'rol', 'x': 146, 'y': 633, 'kind': 'simple', 'owner': 'Usuario'},
 {'id': 'Usuario.nickname', 'label': 'nickname', 'x': 18, 'y': 520, 'kind': 'simple', 'owner': 'Usuario'},
 {'id': 'Usuario.correo', 'label': 'correo', 'x': -90, 'y': 644, 'kind': 'simple', 'owner': 'Usuario'},
 {'id': 'Usuario.contrasena_hash',
  'label': 'contrasena_hash',
  'x': -186,
  'y': 485,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.contrasena_sal',
  'label': 'contrasena_sal',
  'x': -409,
  'y': 505,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.fecha_nacimiento',
  'label': 'fecha_nacimiento',
  'x': -410,
  'y': 320,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.idioma_preferido',
  'label': 'idioma_preferido',
  'x': -475,
  'y': 212,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.intentos_fallidos',
  'label': 'intentos_fallidos',
  'x': -510,
  'y': 99,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.fecha_ultimo_intento_fallido',
  'label': 'fecha_ultimo_intento_fallido',
  'x': -650,
  'y': -11,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.bloqueada_hasta',
  'label': 'bloqueada_hasta',
  'x': -638,
  'y': -124,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.doble_factor_habilitado',
  'label': 'doble_factor_habilitado',
  'x': -607,
  'y': -233,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.fecha_registro',
  'label': 'fecha_registro',
  'x': -551,
  'y': -344,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.fecha_ultimo_envio_verificacion',
  'label': 'fecha_ultimo_envio_verificacion',
  'x': -468,
  'y': -452,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.fecha_ultimo_envio_recuperacion',
  'label': 'fecha_ultimo_envio_recuperacion',
  'x': -325,
  'y': -563,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.version_terminos',
  'label': 'version_terminos',
  'x': -27,
  'y': -519,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.idioma_terminos',
  'label': 'idioma_terminos',
  'x': 113,
  'y': -640,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.fecha_aceptacion_terminos',
  'label': 'fecha_aceptacion_terminos',
  'x': 244,
  'y': -459,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Usuario.fecha_baja',
  'label': 'fecha_baja',
  'x': 386,
  'y': -348,
  'kind': 'simple',
  'owner': 'Usuario'},
 {'id': 'Sesion.id_sesion', 'label': 'id_sesion', 'x': 903, 'y': -740, 'kind': 'key', 'owner': 'Sesion'},
 {'id': 'Sesion.token_hash',
  'label': 'token_hash',
  'x': 1085,
  'y': -749,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.fecha_inicio',
  'label': 'fecha_inicio',
  'x': 1256,
  'y': -683,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.fecha_expiracion',
  'label': 'fecha_expiracion',
  'x': 1381,
  'y': -560,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.fecha_ultimo_uso',
  'label': 'fecha_ultimo_uso',
  'x': 1438,
  'y': -435,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.fecha_fin', 'label': 'fecha_fin', 'x': 1455, 'y': -321, 'kind': 'simple', 'owner': 'Sesion'},
 {'id': 'Sesion.motivo_cierre',
  'label': 'motivo_cierre',
  'x': 1443,
  'y': -215,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.direccion_ip',
  'label': 'direccion_ip',
  'x': 1395,
  'y': -94,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.huella_dispositivo',
  'label': 'huella_dispositivo',
  'x': 1285,
  'y': 33,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.nombre_dispositivo',
  'label': 'nombre_dispositivo',
  'x': 1067,
  'y': 122,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'Sesion.version_cliente',
  'label': 'version_cliente',
  'x': 835,
  'y': 86,
  'kind': 'simple',
  'owner': 'Sesion'},
 {'id': 'CodigoVerificacion.id_codigo',
  'label': 'id_codigo',
  'x': 1395,
  'y': 163,
  'kind': 'key',
  'owner': 'CodigoVerificacion'},
 {'id': 'CodigoVerificacion.proposito',
  'label': 'proposito',
  'x': 1441,
  'y': 277,
  'kind': 'simple',
  'owner': 'CodigoVerificacion'},
 {'id': 'CodigoVerificacion.codigo_hash',
  'label': 'codigo_hash',
  'x': 1455,
  'y': 391,
  'kind': 'simple',
  'owner': 'CodigoVerificacion'},
 {'id': 'CodigoVerificacion.correo_destino',
  'label': 'correo_destino',
  'x': 1438,
  'y': 504,
  'kind': 'simple',
  'owner': 'CodigoVerificacion'},
 {'id': 'CodigoVerificacion.fecha_generacion',
  'label': 'fecha_generacion',
  'x': 1381,
  'y': 629,
  'kind': 'simple',
  'owner': 'CodigoVerificacion'},
 {'id': 'CodigoVerificacion.fecha_expiracion',
  'label': 'fecha_expiracion',
  'x': 1250,
  'y': 757,
  'kind': 'simple',
  'owner': 'CodigoVerificacion'},
 {'id': 'CodigoVerificacion.intentos',
  'label': 'intentos',
  'x': 1063,
  'y': 822,
  'kind': 'simple',
  'owner': 'CodigoVerificacion'},
 {'id': 'CodigoVerificacion.estado',
  'label': 'estado',
  'x': 888,
  'y': 806,
  'kind': 'simple',
  'owner': 'CodigoVerificacion'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
