# -*- coding: utf-8 -*-
"""Modelo E-R «Catálogos de la fase posterior», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion fp-catalogos"""

ENTITIES = {'Ranura': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'ObjetoCosmetico': {'x': 1150, 'y': 0, 'w': 293, 'h': 110, 'kind': 'strong'},
 'Division': {'x': 575, 'y': 1350, 'w': 290, 'h': 110, 'kind': 'strong'},
 'NivelIA': {'x': 1700, 'y': 1350, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Leccion': {'x': 2800, 'y': 1350, 'w': 290, 'h': 110, 'kind': 'strong'},
 'TipoCaja': {'x': 3300, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'TipoCajaObjeto': {'x': 2250, 'y': 0, 'w': 290, 'h': 110, 'kind': 'weak'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_ObjetoCosmetico_Ranura',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('ObjetoCosmetico', '1', 'N', True, False, None), ('Ranura', '1', '1', True, True, None)],
  'x': 575,
  'y': 0},
 {'id': 'FK_TipoCajaObjeto_TipoCaja',
  'label': 'Ofrece',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('TipoCaja', '1', '1', True, True, None), ('TipoCajaObjeto', 'N', '1', True, False, None)],
  'x': 2775,
  'y': 0},
 {'id': 'FK_TipoCajaObjeto_ObjetoCosmetico',
  'label': 'Sortea',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('TipoCajaObjeto', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': 1700,
  'y': 0}]

ATTRS = [{'id': 'ObjetoCosmetico.id_objeto',
  'label': 'id_objeto',
  'x': 1519,
  'y': 240,
  'kind': 'key',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.codigo',
  'label': 'codigo',
  'x': 1546,
  'y': 410,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.rareza',
  'label': 'rareza',
  'x': 1363,
  'y': 385,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.precio',
  'label': 'precio',
  'x': 1307,
  'y': 548,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.nivel_requerido',
  'label': 'nivel_requerido',
  'x': 1150,
  'y': 440,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.a_la_venta',
  'label': 'a_la_venta',
  'x': 1002,
  'y': 551,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.activo',
  'label': 'activo',
  'x': 943,
  'y': 388,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.es_inicial',
  'label': 'es_inicial',
  'x': 761,
  'y': 417,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'ObjetoCosmetico.es_predeterminado',
  'label': 'es_predeterminado',
  'x': 672,
  'y': 310,
  'kind': 'simple',
  'owner': 'ObjetoCosmetico'},
 {'id': 'Division.id_division',
  'label': 'id_division',
  'x': 272,
  'y': 1031,
  'kind': 'key',
  'owner': 'Division'},
 {'id': 'Division.codigo', 'label': 'codigo', 'x': 414, 'y': 940, 'kind': 'simple', 'owner': 'Division'},
 {'id': 'Division.elo_minimo',
  'label': 'elo_minimo',
  'x': 587,
  'y': 910,
  'kind': 'simple',
  'owner': 'Division'},
 {'id': 'Division.elo_descenso',
  'label': 'elo_descenso',
  'x': 765,
  'y': 953,
  'kind': 'simple',
  'owner': 'Division'},
 {'id': 'Leccion.id_leccion', 'label': 'id_leccion', 'x': 2503, 'y': 1025, 'kind': 'key', 'owner': 'Leccion'},
 {'id': 'Leccion.codigo', 'label': 'codigo', 'x': 2639, 'y': 940, 'kind': 'simple', 'owner': 'Leccion'},
 {'id': 'Leccion.orden', 'label': 'orden', 'x': 2812, 'y': 910, 'kind': 'simple', 'owner': 'Leccion'},
 {'id': 'Leccion.num_pasos', 'label': 'num_pasos', 'x': 2983, 'y': 950, 'kind': 'simple', 'owner': 'Leccion'},
 {'id': 'TipoCaja.id_tipo_caja',
  'label': 'id_tipo_caja',
  'x': 3699,
  'y': -185,
  'kind': 'key',
  'owner': 'TipoCaja'},
 {'id': 'TipoCaja.codigo', 'label': 'codigo', 'x': 3735, 'y': -67, 'kind': 'simple', 'owner': 'TipoCaja'},
 {'id': 'TipoCaja.precio', 'label': 'precio', 'x': 3738, 'y': 40, 'kind': 'simple', 'owner': 'TipoCaja'},
 {'id': 'TipoCaja.activo', 'label': 'activo', 'x': 3713, 'y': 152, 'kind': 'simple', 'owner': 'TipoCaja'},
 {'id': 'NivelIA.id_nivel_ia',
  'label': 'id_nivel_ia',
  'x': 1464,
  'y': 979,
  'kind': 'key',
  'owner': 'NivelIA'},
 {'id': 'NivelIA.codigo', 'label': 'codigo', 'x': 1628, 'y': 916, 'kind': 'simple', 'owner': 'NivelIA'},
 {'id': 'NivelIA.elo_aproximado',
  'label': 'elo_aproximado',
  'x': 1826,
  'y': 928,
  'kind': 'simple',
  'owner': 'NivelIA'},
 {'id': 'Ranura.id_ranura', 'label': 'id_ranura', 'x': -416, 'y': 143, 'kind': 'key', 'owner': 'Ranura'},
 {'id': 'Ranura.codigo', 'label': 'codigo', 'x': -439, 'y': 30, 'kind': 'simple', 'owner': 'Ranura'},
 {'id': 'TipoCajaObjeto.probabilidad',
  'label': 'probabilidad',
  'x': 2311,
  'y': 436,
  'kind': 'simple',
  'owner': 'TipoCajaObjeto'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
