# -*- coding: utf-8 -*-
"""Modelo E-R «Aspecto en partida, espectador e invitaciones», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion fp-partida"""

ENTITIES = {'ParticipacionObjeto': {'x': 1200, 'y': -450, 'w': 356, 'h': 110, 'kind': 'weak'},
 'EnlaceEspectador': {'x': 1200, 'y': 500, 'w': 309, 'h': 110, 'kind': 'strong'},
 'Invitacion': {'x': -1300, 'y': 800, 'w': 290, 'h': 110, 'kind': 'strong'},
 'ObjetoCosmetico': {'x': 2400, 'y': -450, 'w': 293, 'h': 110, 'kind': 'strong'},
 'Participacion': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Sala': {'x': -1300, 'y': 1800, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': -2500, 'y': 800, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_ParticipacionObjeto_Participacion',
  'label': 'Fija',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Participacion', '1', '1', True, True, None),
           ('ParticipacionObjeto', 'N', '1', True, False, None)],
  'x': 600,
  'y': -225},
 {'id': 'FK_ParticipacionObjeto_ObjetoCosmetico',
  'label': 'Luce',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('ParticipacionObjeto', '1', 'N', True, False, None),
           ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': 1800,
  'y': -450},
 {'id': 'FK_EnlaceEspectador_Participacion',
  'label': 'Comparte',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('EnlaceEspectador', 'N', '1', True, False, None)],
  'x': 600,
  'y': 250},
 {'id': 'FK_Invitacion_Sala',
  'label': 'Da acceso a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Invitacion', '1', 'N', True, False, None), ('Sala', '1', '1', False, True, None)],
  'x': -1300,
  'y': 1300},
 {'id': 'FK_Invitacion_Emisor',
  'label': 'Envía',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'emisor'), ('Invitacion', 'N', '1', True, False, None)],
  'x': -1900,
  'y': 950},
 {'id': 'FK_Invitacion_Destinatario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'destinatario'), ('Invitacion', 'N', '1', True, False, None)],
  'x': -1900,
  'y': 650}]

ATTRS = [{'id': 'Invitacion.id_invitacion',
  'label': 'id_invitacion',
  'x': -1258,
  'y': 362,
  'kind': 'key',
  'owner': 'Invitacion'},
 {'id': 'Invitacion.fecha_invitacion',
  'label': 'fecha_invitacion',
  'x': -1063,
  'y': 429,
  'kind': 'simple',
  'owner': 'Invitacion'},
 {'id': 'Invitacion.fecha_expiracion',
  'label': 'fecha_expiracion',
  'x': -933,
  'y': 557,
  'kind': 'simple',
  'owner': 'Invitacion'},
 {'id': 'Invitacion.estado', 'label': 'estado', 'x': -878, 'y': 675, 'kind': 'simple', 'owner': 'Invitacion'},
 {'id': 'EnlaceEspectador.id_enlace',
  'label': 'id_enlace',
  'x': 1640,
  'y': 493,
  'kind': 'key',
  'owner': 'EnlaceEspectador'},
 {'id': 'EnlaceEspectador.token_hash',
  'label': 'token_hash',
  'x': 1629,
  'y': 599,
  'kind': 'simple',
  'owner': 'EnlaceEspectador'},
 {'id': 'EnlaceEspectador.fecha_creacion',
  'label': 'fecha_creacion',
  'x': 1585,
  'y': 713,
  'kind': 'simple',
  'owner': 'EnlaceEspectador'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
