# -*- coding: utf-8 -*-
"""Modelo E-R «Vista general», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion general"""

ENTITIES = {'Ranura': {'x': -5505, 'y': 3920, 'w': 290, 'h': 110, 'kind': 'strong'},
 'ObjetoCosmetico': {'x': -4891, 'y': 1689, 'w': 293, 'h': 110, 'kind': 'strong'},
 'Modo': {'x': 177, 'y': -4454, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Division': {'x': 3132, 'y': -5314, 'w': 290, 'h': 110, 'kind': 'strong'},
 'NivelIA': {'x': -1650, 'y': -6245, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Leccion': {'x': 4472, 'y': 3899, 'w': 290, 'h': 110, 'kind': 'strong'},
 'TipoCaja': {'x': -6651, 'y': -97, 'w': 290, 'h': 110, 'kind': 'strong'},
 'TipoCajaObjeto': {'x': -7205, 'y': 1414, 'w': 290, 'h': 110, 'kind': 'weak'},
 'PalabraProhibida': {'x': -3405, 'y': 1156, 'w': 309, 'h': 110, 'kind': 'strong'},
 'MotivoReporte': {'x': -4304, 'y': -2499, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Sesion': {'x': 791, 'y': 3445, 'w': 290, 'h': 110, 'kind': 'strong'},
 'CodigoSegundoFactor': {'x': 2472, 'y': -1786, 'w': 356, 'h': 110, 'kind': 'strong'},
 'TokenVerificacionCorreo': {'x': -74, 'y': 2673, 'w': 419, 'h': 110, 'kind': 'strong'},
 'TokenRecuperacion': {'x': 2731, 'y': 1102, 'w': 325, 'h': 110, 'kind': 'strong'},
 'AceptacionTerminos': {'x': -1428, 'y': 2415, 'w': 340, 'h': 110, 'kind': 'strong'},
 'HistorialNickname': {'x': 3490, 'y': 173, 'w': 325, 'h': 110, 'kind': 'weak'},
 'Avatar': {'x': 3281, 'y': -957, 'w': 290, 'h': 110, 'kind': 'strong'},
 'EnlaceRed': {'x': -918, 'y': 3472, 'w': 290, 'h': 110, 'kind': 'strong'},
 'UsuarioObjeto': {'x': -2918, 'y': 2124, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Equipamiento': {'x': -4330, 'y': 3569, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Partida': {'x': -1937, 'y': -3805, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Participacion': {'x': -3149, 'y': -2497, 'w': 290, 'h': 110, 'kind': 'weak'},
 'ParticipacionObjeto': {'x': -5048, 'y': -765, 'w': 356, 'h': 110, 'kind': 'weak'},
 'Jugada': {'x': -3188, 'y': -4760, 'w': 290, 'h': 110, 'kind': 'weak'},
 'OfertaTablas': {'x': -5702, 'y': -3439, 'w': 290, 'h': 110, 'kind': 'strong'},
 'EnlaceEspectador': {'x': -4760, 'y': -4557, 'w': 309, 'h': 110, 'kind': 'strong'},
 'ColaEmparejamiento': {'x': 767, 'y': -2948, 'w': 340, 'h': 110, 'kind': 'weak'},
 'Sala': {'x': -457, 'y': -2874, 'w': 290, 'h': 110, 'kind': 'strong'},
 'SalaParticipante': {'x': -671, 'y': -1625, 'w': 309, 'h': 110, 'kind': 'weak'},
 'Invitacion': {'x': 489, 'y': -1737, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Mensaje': {'x': -1528, 'y': -2413, 'w': 290, 'h': 110, 'kind': 'strong'},
 'EstadisticaModo': {'x': 1978, 'y': -3507, 'w': 293, 'h': 110, 'kind': 'weak'},
 'HistorialDivision': {'x': 3916, 'y': -4449, 'w': 325, 'h': 110, 'kind': 'strong'},
 'Caja': {'x': -3799, 'y': 208, 'w': 290, 'h': 110, 'kind': 'strong'},
 'CajaContenido': {'x': -5747, 'y': 919, 'w': 290, 'h': 110, 'kind': 'weak'},
 'MovimientoMoneda': {'x': -2932, 'y': -613, 'w': 309, 'h': 110, 'kind': 'strong'},
 'Amistad': {'x': 2069, 'y': -39, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Solicitud': {'x': -751, 'y': 1140, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Silencio': {'x': 358, 'y': 1513, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Bloqueo': {'x': 1325, 'y': 875, 'w': 290, 'h': 110, 'kind': 'weak'},
 'ProgresoTutorial': {'x': 2922, 'y': 2527, 'w': 309, 'h': 110, 'kind': 'weak'},
 'Reporte': {'x': -1946, 'y': -1220, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Sancion': {'x': -1493, 'y': 12, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Apelacion': {'x': -2074, 'y': 1169, 'w': 290, 'h': 110, 'kind': 'strong'},
 'BitacoraModeracion': {'x': 1344, 'y': -941, 'w': 340, 'h': 110, 'kind': 'strong'},
 'BitacoraAcceso': {'x': 1586, 'y': 2472, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_ObjetoCosmetico_Ranura',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('ObjetoCosmetico', '1', 'N', True, False, None), ('Ranura', '1', '1', True, True, None)],
  'x': -5198,
  'y': 2804},
 {'id': 'FK_TipoCajaObjeto_TipoCaja',
  'label': 'Ofrece',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('TipoCaja', '1', '1', True, True, None), ('TipoCajaObjeto', 'N', '1', True, False, None)],
  'x': -6928,
  'y': 658},
 {'id': 'FK_TipoCajaObjeto_ObjetoCosmetico',
  'label': 'Sortea',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('TipoCajaObjeto', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': -6048,
  'y': 1552},
 {'id': 'FK_Sesion_Usuario',
  'label': 'Abre',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('Sesion', 'N', '1', True, False, None)],
  'x': 396,
  'y': 1722},
 {'id': 'FK_CodigoSegundoFactor_Usuario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('CodigoSegundoFactor', 'N', '1', True, False, None)],
  'x': 1033,
  'y': -747},
 {'id': 'FK_TokenVerificacionCorreo_Usuario',
  'label': 'Verifica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None),
           ('TokenVerificacionCorreo', 'N', '1', True, False, None)],
  'x': -37,
  'y': 1336},
 {'id': 'FK_TokenRecuperacion_Usuario',
  'label': 'Recupera',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('TokenRecuperacion', 'N', '1', True, False, None)],
  'x': 1366,
  'y': 551},
 {'id': 'FK_AceptacionTerminos_Usuario',
  'label': 'Acepta',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('AceptacionTerminos', 'N', '1', True, False, None)],
  'x': -790,
  'y': 1337},
 {'id': 'FK_HistorialNickname_Usuario',
  'label': 'Cambia nombre',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('HistorialNickname', '1', '1', True, False, None)],
  'x': 1745,
  'y': 86},
 {'id': 'FK_Avatar_Usuario',
  'label': 'Sube',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('Avatar', 'N', '1', True, False, None)],
  'x': 1640,
  'y': -478},
 {'id': 'FK_EnlaceRed_Usuario',
  'label': 'Publica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('EnlaceRed', 'N', '1', True, False, None)],
  'x': -459,
  'y': 1736},
 {'id': 'FK_UsuarioObjeto_Usuario',
  'label': 'Posee',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', True, True, None), ('UsuarioObjeto', 'N', '1', True, False, None)],
  'x': -1459,
  'y': 1062},
 {'id': 'FK_UsuarioObjeto_ObjetoCosmetico',
  'label': 'Corresponde a',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('UsuarioObjeto', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': -3904,
  'y': 1906},
 {'id': 'FK_Equipamiento_UsuarioObjeto',
  'label': 'Usa',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Equipamiento', '1', '1', True, False, None), ('UsuarioObjeto', '1', '1', False, True, None)],
  'x': -3624,
  'y': 2846},
 {'id': 'FK_Equipamiento_ObjetoCosmetico',
  'label': 'Muestra',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('Equipamiento', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': -4610,
  'y': 2629},
 {'id': 'FK_Equipamiento_Ranura',
  'label': 'Ocupa',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('Equipamiento', '1', 'N', True, False, None), ('Ranura', '1', '1', False, True, None)],
  'x': -4918,
  'y': 3744},
 {'id': 'FK_Partida_Modo',
  'label': 'Se juega en',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Partida', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': -880,
  'y': -4130},
 {'id': 'FK_Partida_NivelIA',
  'label': 'Enfrenta',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Partida', '1', 'N', False, False, None), ('NivelIA', '1', '1', False, True, None)],
  'x': -1794,
  'y': -5025},
 {'id': 'FK_Participacion_Partida',
  'label': 'Reúne',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', True, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': -2543,
  'y': -3151},
 {'id': 'FK_Participacion_Usuario',
  'label': 'Participa',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': -1574,
  'y': -1248},
 {'id': 'FK_ParticipacionObjeto_Participacion',
  'label': 'Fija',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Participacion', '1', '1', True, True, None),
           ('ParticipacionObjeto', 'N', '1', True, False, None)],
  'x': -4098,
  'y': -1631},
 {'id': 'FK_ParticipacionObjeto_ObjetoCosmetico',
  'label': 'Luce',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('ParticipacionObjeto', '1', 'N', True, False, None),
           ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': -4980,
  'y': 312},
 {'id': 'FK_Jugada_Partida',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', False, True, None), ('Jugada', 'N', '1', True, False, None)],
  'x': -2562,
  'y': -4282},
 {'id': 'FK_Jugada_Participacion',
  'label': 'Hace',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('Jugada', 'N', '1', False, False, None)],
  'x': -3168,
  'y': -3628},
 {'id': 'FK_OfertaTablas_Participacion',
  'label': 'Ofrece',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('OfertaTablas', 'N', '1', True, False, None)],
  'x': -4426,
  'y': -2968},
 {'id': 'FK_EnlaceEspectador_Participacion',
  'label': 'Comparte',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('EnlaceEspectador', 'N', '1', True, False, None)],
  'x': -3954,
  'y': -3527},
 {'id': 'FK_ColaEmparejamiento_Usuario',
  'label': 'Espera en',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('ColaEmparejamiento', '1', '1', True, False, None)],
  'x': 384,
  'y': -1474},
 {'id': 'FK_ColaEmparejamiento_Modo',
  'label': 'Busca',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('ColaEmparejamiento', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 472,
  'y': -3701},
 {'id': 'FK_Sala_Anfitrion',
  'label': 'Crea',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'anfitrión'), ('Sala', 'N', '1', True, False, None)],
  'x': -228,
  'y': -1437},
 {'id': 'FK_Sala_Modo',
  'label': 'Usa',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Sala', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': -140,
  'y': -3664},
 {'id': 'FK_Sala_Partida',
  'label': 'Inicia',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sala', '1', '1', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': -1197,
  'y': -3340},
 {'id': 'FK_SalaParticipante_Sala',
  'label': 'Admite',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Sala', '1', '1', False, True, None), ('SalaParticipante', 'N', '1', True, False, None)],
  'x': -564,
  'y': -2250},
 {'id': 'FK_SalaParticipante_Usuario',
  'label': 'Ocupa',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('SalaParticipante', '1', '1', True, False, None)],
  'x': -336,
  'y': -812},
 {'id': 'FK_Invitacion_Sala',
  'label': 'Da acceso a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Invitacion', '1', 'N', True, False, None), ('Sala', '1', '1', False, True, None)],
  'x': 16,
  'y': -2306},
 {'id': 'FK_Invitacion_Emisor',
  'label': 'Envía',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'emisor'), ('Invitacion', 'N', '1', True, False, None)],
  'x': 389,
  'y': -828},
 {'id': 'FK_Invitacion_Destinatario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'destinatario'), ('Invitacion', 'N', '1', True, False, None)],
  'x': 100,
  'y': -909},
 {'id': 'FK_Mensaje_Autor',
  'label': 'Escribe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'autor'), ('Mensaje', 'N', '1', True, False, None)],
  'x': -764,
  'y': -1206},
 {'id': 'FK_Mensaje_Partida',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': -1732,
  'y': -3109},
 {'id': 'FK_Mensaje_Sala',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Sala', '1', '1', False, True, None)],
  'x': -992,
  'y': -2644},
 {'id': 'FK_EstadisticaModo_Usuario',
  'label': 'Tiene',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', True, True, None), ('EstadisticaModo', 'N', '1', True, False, None)],
  'x': 989,
  'y': -1754},
 {'id': 'FK_EstadisticaModo_Modo',
  'label': 'Mide',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('EstadisticaModo', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 1078,
  'y': -3980},
 {'id': 'FK_EstadisticaModo_Division',
  'label': 'Ubica en',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('EstadisticaModo', '1', 'N', False, False, None), ('Division', '1', '1', False, True, None)],
  'x': 2555,
  'y': -4410},
 {'id': 'FK_HistorialDivision_EstadisticaModo',
  'label': 'Acumula',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('EstadisticaModo', '1', '1', False, True, None),
           ('HistorialDivision', 'N', '1', True, False, None)],
  'x': 2947,
  'y': -3978},
 {'id': 'FK_HistorialDivision_Anterior',
  'label': 'Sale de',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('HistorialDivision', '1', 'N', False, False, None),
           ('Division', '1', '1', False, True, 'anterior')],
  'x': 3601,
  'y': -5019},
 {'id': 'FK_HistorialDivision_Nueva',
  'label': 'Llega a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('HistorialDivision', '1', 'N', True, False, None), ('Division', '1', '1', False, True, 'nueva')],
  'x': 3413,
  'y': -4781},
 {'id': 'FK_Caja_Usuario',
  'label': 'Obtiene',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('Caja', 'N', '1', True, False, None)],
  'x': -1900,
  'y': 104},
 {'id': 'FK_Caja_TipoCaja',
  'label': 'Es de tipo',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Caja', '1', 'N', True, False, None), ('TipoCaja', '1', '1', False, True, None)],
  'x': -5225,
  'y': 56},
 {'id': 'FK_CajaContenido_Caja',
  'label': 'Contiene',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Caja', '1', '1', False, True, None), ('CajaContenido', 'N', '1', True, False, None)],
  'x': -4773,
  'y': 564},
 {'id': 'FK_CajaContenido_ObjetoCosmetico',
  'label': 'Entrega',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('CajaContenido', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': -5319,
  'y': 1304},
 {'id': 'FK_MovimientoMoneda_Usuario',
  'label': 'Mueve',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('MovimientoMoneda', 'N', '1', True, False, None)],
  'x': -1466,
  'y': -306},
 {'id': 'FK_MovimientoMoneda_Partida',
  'label': 'Paga',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Partida', '1', '1', False, True, None), ('MovimientoMoneda', 'N', '1', False, False, None)],
  'x': -2434,
  'y': -2209},
 {'id': 'FK_MovimientoMoneda_ObjetoCosmetico',
  'label': 'Paga',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('MovimientoMoneda', '1', 'N', False, False, None),
           ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': -3912,
  'y': 538},
 {'id': 'FK_MovimientoMoneda_Caja',
  'label': 'Origina',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Caja', '1', '1', False, True, None), ('MovimientoMoneda', 'N', '1', False, False, None)],
  'x': -3366,
  'y': -202},
 {'id': 'FK_Amistad_UsuarioA',
  'label': 'Es amigo',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'menor'), ('Amistad', 'N', '1', True, False, None)],
  'x': 1037,
  'y': 130},
 {'id': 'FK_Amistad_UsuarioB',
  'label': 'Es amigo',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'mayor'), ('Amistad', 'N', '1', True, False, None)],
  'x': 1082,
  'y': -170},
 {'id': 'FK_Solicitud_Solicitante',
  'label': 'Envía',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'solicitante'), ('Solicitud', 'N', '1', True, False, None)],
  'x': -556,
  'y': 571},
 {'id': 'FK_Solicitud_Destinatario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'destinatario'), ('Solicitud', 'N', '1', True, False, None)],
  'x': -195,
  'y': 569},
 {'id': 'FK_Silencio_Usuario',
  'label': 'Silencia',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'quien silencia'), ('Silencio', 'N', '1', True, False, None)],
  'x': 33,
  'y': 791},
 {'id': 'FK_Silencio_Silenciado',
  'label': 'Es silenciado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'silenciado'), ('Silencio', 'N', '1', True, False, None)],
  'x': 348,
  'y': 819},
 {'id': 'FK_Bloqueo_Bloqueador',
  'label': 'Bloquea',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueador'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 580,
  'y': 563},
 {'id': 'FK_Bloqueo_Bloqueado',
  'label': 'Es bloqueado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueado'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 745,
  'y': 312},
 {'id': 'FK_ProgresoTutorial_Usuario',
  'label': 'Avanza',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('ProgresoTutorial', 'N', '1', True, False, None)],
  'x': 1461,
  'y': 1264},
 {'id': 'FK_ProgresoTutorial_Leccion',
  'label': 'Cubre',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('ProgresoTutorial', '1', 'N', True, False, None), ('Leccion', '1', '1', False, True, None)],
  'x': 3697,
  'y': 3213},
 {'id': 'FK_Reporte_Denunciante',
  'label': 'Emite',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'reportante'), ('Reporte', 'N', '1', True, False, None)],
  'x': -814,
  'y': -864},
 {'id': 'FK_Reporte_Reportado',
  'label': 'Señala',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', True, False, None), ('Usuario', '1', '1', False, True, 'reportado')],
  'x': -1100,
  'y': -690},
 {'id': 'FK_Reporte_MotivoReporte',
  'label': 'Clasifica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('MotivoReporte', '1', '1', False, True, None), ('Reporte', 'N', '1', True, False, None)],
  'x': -3125,
  'y': -1860},
 {'id': 'FK_Reporte_ParticipacionDenunciante',
  'label': 'Sobre',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', False, False, None),
           ('Participacion', '1', '1', False, True, 'del reportante')],
  'x': -2369,
  'y': -1888},
 {'id': 'FK_Reporte_ParticipacionReportado',
  'label': 'Sobre',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', False, False, None),
           ('Participacion', '1', '1', False, True, 'del reportado')],
  'x': -2657,
  'y': -1756},
 {'id': 'FK_Reporte_Moderador',
  'label': 'Revisa',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Reporte', 'N', '1', False, False, None)],
  'x': -1132,
  'y': -356},
 {'id': 'FK_Sancion_Usuario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'sancionado'), ('Sancion', 'N', '1', True, False, None)],
  'x': -748,
  'y': -144},
 {'id': 'FK_Sancion_Moderador',
  'label': 'Aplica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Sancion', 'N', '1', True, False, None)],
  'x': -745,
  'y': 156},
 {'id': 'FK_Sancion_Reporte',
  'label': 'Origina',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Reporte', '1', '1', False, True, None), ('Sancion', 'N', '1', False, False, None)],
  'x': -1720,
  'y': -604},
 {'id': 'FK_Sancion_Sustituta',
  'label': 'Sustituye',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sancion', '1', '1', False, True, 'sustituta'),
           ('Sancion', '1', '1', False, False, 'sustituida')],
  'x': -793,
  'y': -488},
 {'id': 'FK_Apelacion_Sancion',
  'label': 'Se apela',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sancion', '1', '1', False, True, None), ('Apelacion', '1', '1', True, False, None)],
  'x': -1784,
  'y': 590},
 {'id': 'FK_Apelacion_Moderador',
  'label': 'Resuelve',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Apelacion', 'N', '1', False, False, None)],
  'x': -1037,
  'y': 584},
 {'id': 'FK_BitacoraModeracion_Moderador',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'autor'), ('BitacoraModeracion', 'N', '1', True, False, None)],
  'x': 758,
  'y': -348},
 {'id': 'FK_BitacoraModeracion_Afectado',
  'label': 'Afecta',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('BitacoraModeracion', '1', 'N', False, False, None),
           ('Usuario', '1', '1', False, True, 'afectado')],
  'x': 586,
  'y': -593},
 {'id': 'FK_BitacoraAcceso_Usuario',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('BitacoraAcceso', 'N', '1', False, False, None)],
  'x': 793,
  'y': 1236}]

ATTRS = []

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
