# -*- coding: utf-8 -*-
"""Modelo E-R «Vista general del núcleo», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion general"""

ENTITIES = {'Modo': {'x': 1124, 'y': 3392, 'w': 290, 'h': 110, 'kind': 'strong'},
 'PalabraProhibida': {'x': -2100, 'y': 375, 'w': 309, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Sesion': {'x': -2323, 'y': -588, 'w': 290, 'h': 110, 'kind': 'strong'},
 'CodigoVerificacion': {'x': 2294, 'y': -647, 'w': 340, 'h': 110, 'kind': 'strong'},
 'Partida': {'x': -690, 'y': 3121, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Participacion': {'x': -1882, 'y': 1708, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Jugada': {'x': -2155, 'y': 3348, 'w': 290, 'h': 110, 'kind': 'weak'},
 'OfertaTablas': {'x': -3800, 'y': 1936, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Sala': {'x': 416, 'y': 2260, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Mensaje': {'x': -458, 'y': 1822, 'w': 290, 'h': 110, 'kind': 'strong'},
 'EstadisticaModo': {'x': 1629, 'y': 1816, 'w': 293, 'h': 110, 'kind': 'weak'},
 'Silencio': {'x': -25, 'y': -1494, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Bloqueo': {'x': 1545, 'y': 326, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Reporte': {'x': -1221, 'y': 524, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Sancion': {'x': -1167, 'y': -648, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Apelacion': {'x': -1316, 'y': -1784, 'w': 290, 'h': 110, 'kind': 'strong'},
 'BitacoraModeracion': {'x': 1140, 'y': -823, 'w': 340, 'h': 110, 'kind': 'strong'},
 'BitacoraAcceso': {'x': 1017, 'y': -2175, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_Sesion_Usuario',
  'label': 'Abre',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('Sesion', 'N', '1', True, False, None)],
  'x': -1162,
  'y': -294},
 {'id': 'FK_CodigoVerificacion_Usuario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('CodigoVerificacion', 'N', '1', True, False, None)],
  'x': 1147,
  'y': -324},
 {'id': 'FK_Partida_Modo',
  'label': 'Se juega en',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Partida', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 217,
  'y': 3256},
 {'id': 'FK_Participacion_Partida',
  'label': 'Reúne',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', True, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': -1286,
  'y': 2414},
 {'id': 'FK_Participacion_Usuario',
  'label': 'Participa',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': -941,
  'y': 854},
 {'id': 'FK_Jugada_Partida',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', False, True, None), ('Jugada', 'N', '1', True, False, None)],
  'x': -1422,
  'y': 3234},
 {'id': 'FK_Jugada_Participacion',
  'label': 'Hace',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Participacion', '1', '1', False, True, None), ('Jugada', 'N', '1', True, False, None)],
  'x': -2018,
  'y': 2528},
 {'id': 'FK_OfertaTablas_Participacion',
  'label': 'Ofrece',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('OfertaTablas', 'N', '1', True, False, None)],
  'x': -2841,
  'y': 1822},
 {'id': 'FK_Sala_Anfitrion',
  'label': 'Crea',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'anfitrión'), ('Sala', 'N', '1', True, False, None)],
  'x': 208,
  'y': 1130},
 {'id': 'FK_Sala_Modo',
  'label': 'Usa',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Sala', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 770,
  'y': 2826},
 {'id': 'FK_Sala_Partida',
  'label': 'Inicia',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sala', '1', '1', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': -137,
  'y': 2690},
 {'id': 'FK_Mensaje_Autor',
  'label': 'Escribe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'autor'), ('Mensaje', 'N', '1', True, False, None)],
  'x': -229,
  'y': 911},
 {'id': 'FK_Mensaje_Partida',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': -574,
  'y': 2472},
 {'id': 'FK_Mensaje_Sala',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Sala', '1', '1', False, True, None)],
  'x': -21,
  'y': 2041},
 {'id': 'FK_EstadisticaModo_Usuario',
  'label': 'Tiene',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', True, True, None), ('EstadisticaModo', 'N', '1', True, False, None)],
  'x': 814,
  'y': 908},
 {'id': 'FK_EstadisticaModo_Modo',
  'label': 'Mide',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('EstadisticaModo', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 1376,
  'y': 2604},
 {'id': 'FK_Silencio_Usuario',
  'label': 'Silencia',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'quien silencia'), ('Silencio', 'N', '1', True, False, None)],
  'x': 137,
  'y': -750},
 {'id': 'FK_Silencio_Silenciado',
  'label': 'Es silenciado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'silenciado'), ('Silencio', 'N', '1', True, False, None)],
  'x': -162,
  'y': -744},
 {'id': 'FK_Bloqueo_Bloqueador',
  'label': 'Bloquea',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueador'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 742,
  'y': 310},
 {'id': 'FK_Bloqueo_Bloqueado',
  'label': 'Es bloqueado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueado'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 803,
  'y': 16},
 {'id': 'FK_Reporte_Denunciante',
  'label': 'Emite',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'reportante'), ('Reporte', 'N', '1', True, False, None)],
  'x': -821,
  'y': 25},
 {'id': 'FK_Reporte_Reportado',
  'label': 'Señala',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', True, False, None), ('Usuario', '1', '1', False, True, 'reportado')],
  'x': -610,
  'y': 262},
 {'id': 'FK_Reporte_ParticipacionDenunciante',
  'label': 'Sobre',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', False, False, None),
           ('Participacion', '1', '1', False, True, 'del reportante')],
  'x': -1706,
  'y': 1087},
 {'id': 'FK_Reporte_ParticipacionReportado',
  'label': 'Sobre',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', False, False, None),
           ('Participacion', '1', '1', False, True, 'del reportado')],
  'x': -1421,
  'y': 1189},
 {'id': 'FK_Reporte_Moderador',
  'label': 'Revisa',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Reporte', 'N', '1', False, False, None)],
  'x': -492,
  'y': 538},
 {'id': 'FK_Sancion_Usuario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'sancionado'), ('Sancion', 'N', '1', True, False, None)],
  'x': -511,
  'y': -455},
 {'id': 'FK_Sancion_Moderador',
  'label': 'Aplica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Sancion', 'N', '1', True, False, None)],
  'x': -656,
  'y': -193},
 {'id': 'FK_Sancion_Reporte',
  'label': 'Origina',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Reporte', '1', '1', False, True, None), ('Sancion', 'N', '1', False, False, None)],
  'x': -1194,
  'y': -62},
 {'id': 'FK_Sancion_Sustituta',
  'label': 'Sustituye',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sancion', '1', '1', False, True, 'sustituta'),
           ('Sancion', '1', '1', False, False, 'sustituida')],
  'x': -467,
  'y': -1148},
 {'id': 'FK_Apelacion_Sancion',
  'label': 'Se apela',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sancion', '1', '1', False, True, None), ('Apelacion', '1', '1', True, False, None)],
  'x': -1242,
  'y': -1216},
 {'id': 'FK_Apelacion_Moderador',
  'label': 'Resuelve',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Apelacion', 'N', '1', False, False, None)],
  'x': -658,
  'y': -892},
 {'id': 'FK_BitacoraModeracion_Moderador',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'autor'), ('BitacoraModeracion', 'N', '1', True, False, None)],
  'x': 658,
  'y': -290},
 {'id': 'FK_BitacoraModeracion_Afectado',
  'label': 'Afecta',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('BitacoraModeracion', '1', 'N', False, False, None),
           ('Usuario', '1', '1', False, True, 'afectado')],
  'x': 482,
  'y': -533},
 {'id': 'FK_BitacoraAcceso_Usuario',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('BitacoraAcceso', 'N', '1', False, False, None)],
  'x': 508,
  'y': -1088}]

ATTRS = []

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
