# -*- coding: utf-8 -*-
"""Modelo E-R «Clasificación y relaciones entre jugadores», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion jugadores"""

ENTITIES = {'EstadisticaModo': {'x': -1300, 'y': 0, 'w': 293, 'h': 110, 'kind': 'weak'},
 'Silencio': {'x': 1000, 'y': -600, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Bloqueo': {'x': 1000, 'y': 600, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Modo': {'x': -2500, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_EstadisticaModo_Usuario',
  'label': 'Tiene',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', True, True, None), ('EstadisticaModo', 'N', '1', True, False, None)],
  'x': -650,
  'y': 0},
 {'id': 'FK_EstadisticaModo_Modo',
  'label': 'Mide',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('EstadisticaModo', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': -1900,
  'y': 0},
 {'id': 'FK_Silencio_Usuario',
  'label': 'Silencia',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'quien silencia'), ('Silencio', 'N', '1', True, False, None)],
  'x': 577,
  'y': -171},
 {'id': 'FK_Silencio_Silenciado',
  'label': 'Es silenciado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'silenciado'), ('Silencio', 'N', '1', True, False, None)],
  'x': 423,
  'y': -429},
 {'id': 'FK_Bloqueo_Bloqueador',
  'label': 'Bloquea',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueador'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 423,
  'y': 429},
 {'id': 'FK_Bloqueo_Bloqueado',
  'label': 'Es bloqueado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueado'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 577,
  'y': 171}]

ATTRS = [{'id': 'EstadisticaModo.puntos_elo',
  'label': 'puntos_elo',
  'x': -877,
  'y': 121,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.fecha_ultima_partida',
  'label': 'fecha_ultima_partida',
  'x': -935,
  'y': 246,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.partidas_jugadas',
  'label': 'partidas_jugadas',
  'x': -1080,
  'y': 381,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.partidas_ganadas',
  'label': 'partidas_ganadas',
  'x': -1292,
  'y': 440,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.partidas_perdidas',
  'label': 'partidas_perdidas',
  'x': -1513,
  'y': 385,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.abandonos',
  'label': 'abandonos',
  'x': -1647,
  'y': 271,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'Silencio.fecha_silencio',
  'label': 'fecha_silencio',
  'x': 1337,
  'y': -883,
  'kind': 'simple',
  'owner': 'Silencio'},
 {'id': 'Bloqueo.fecha_bloqueo',
  'label': 'fecha_bloqueo',
  'x': 1402,
  'y': 779,
  'kind': 'simple',
  'owner': 'Bloqueo'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
