# -*- coding: utf-8 -*-
"""Modelo E-R «Moderación y bitácoras», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion moderacion"""

ENTITIES = {'Reporte': {'x': 1170, 'y': -765, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Sancion': {'x': 1170, 'y': 720, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Apelacion': {'x': 1170, 'y': 1665, 'w': 290, 'h': 110, 'kind': 'strong'},
 'BitacoraModeracion': {'x': -1125, 'y': -585, 'w': 340, 'h': 110, 'kind': 'strong'},
 'BitacoraAcceso': {'x': -1125, 'y': 630, 'w': 290, 'h': 110, 'kind': 'strong'},
 'MotivoReporte': {'x': 1170, 'y': -1665, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Participacion': {'x': 2340, 'y': -765, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_Reporte_Denunciante',
  'label': 'Emite',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'reportante'), ('Reporte', 'N', '1', True, False, None)],
  'x': 749,
  'y': -131},
 {'id': 'FK_Reporte_Reportado',
  'label': 'Señala',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', True, False, None), ('Usuario', '1', '1', False, True, 'reportado')],
  'x': 585,
  'y': -382},
 {'id': 'FK_Reporte_MotivoReporte',
  'label': 'Clasifica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('MotivoReporte', '1', '1', False, True, None), ('Reporte', 'N', '1', True, False, None)],
  'x': 1170,
  'y': -1215},
 {'id': 'FK_Reporte_ParticipacionDenunciante',
  'label': 'Sobre',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', False, False, None),
           ('Participacion', '1', '1', False, True, 'del reportante')],
  'x': 1755,
  'y': -615},
 {'id': 'FK_Reporte_ParticipacionReportado',
  'label': 'Sobre',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Reporte', '1', 'N', False, False, None),
           ('Participacion', '1', '1', False, True, 'del reportado')],
  'x': 1755,
  'y': -915},
 {'id': 'FK_Reporte_Moderador',
  'label': 'Revisa',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Reporte', 'N', '1', False, False, None)],
  'x': 421,
  'y': -634},
 {'id': 'FK_Sancion_Usuario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'sancionado'), ('Sancion', 'N', '1', True, False, None)],
  'x': 506,
  'y': 488},
 {'id': 'FK_Sancion_Moderador',
  'label': 'Aplica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Sancion', 'N', '1', True, False, None)],
  'x': 664,
  'y': 232},
 {'id': 'FK_Sancion_Reporte',
  'label': 'Origina',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Reporte', '1', '1', False, True, None), ('Sancion', 'N', '1', False, False, None)],
  'x': 1170,
  'y': -22},
 {'id': 'FK_Sancion_Sustituta',
  'label': 'Sustituye',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sancion', '1', '1', False, True, 'sustituta'),
           ('Sancion', '1', '1', False, False, 'sustituida')],
  'x': 1935,
  'y': 720},
 {'id': 'FK_Apelacion_Sancion',
  'label': 'Se apela',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sancion', '1', '1', False, True, None), ('Apelacion', '1', '1', True, False, None)],
  'x': 1170,
  'y': 1192},
 {'id': 'FK_Apelacion_Moderador',
  'label': 'Resuelve',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'moderador'), ('Apelacion', 'N', '1', False, False, None)],
  'x': 585,
  'y': 832},
 {'id': 'FK_BitacoraModeracion_Moderador',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'autor'), ('BitacoraModeracion', 'N', '1', True, False, None)],
  'x': -493,
  'y': -426},
 {'id': 'FK_BitacoraModeracion_Afectado',
  'label': 'Afecta',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('BitacoraModeracion', '1', 'N', False, False, None),
           ('Usuario', '1', '1', False, True, 'afectado')],
  'x': -632,
  'y': -159},
 {'id': 'FK_BitacoraAcceso_Usuario',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('BitacoraAcceso', 'N', '1', False, False, None)],
  'x': -562,
  'y': 315}]

ATTRS = [{'id': 'Sancion.id_sancion', 'label': 'id_sancion', 'x': 1411, 'y': -43, 'kind': 'key', 'owner': 'Sancion'},
 {'id': 'Sancion.ambito', 'label': 'ambito', 'x': 1599, 'y': -105, 'kind': 'simple', 'owner': 'Sancion'},
 {'id': 'Sancion.tipo', 'label': 'tipo', 'x': 1623, 'y': 61, 'kind': 'simple', 'owner': 'Sancion'},
 {'id': 'Sancion.motivo', 'label': 'motivo', 'x': 1810, 'y': 45, 'kind': 'simple', 'owner': 'Sancion'},
 {'id': 'Sancion.fecha_inicio',
  'label': 'fecha_inicio',
  'x': 1796,
  'y': 222,
  'kind': 'simple',
  'owner': 'Sancion'},
 {'id': 'Sancion.fecha_fin', 'label': 'fecha_fin', 'x': 1987, 'y': 276, 'kind': 'simple', 'owner': 'Sancion'},
 {'id': 'Sancion.fecha_retiro',
  'label': 'fecha_retiro',
  'x': 1914,
  'y': 427,
  'kind': 'simple',
  'owner': 'Sancion'},
 {'id': 'Sancion.activa', 'label': 'activa', 'x': 1948, 'y': 533, 'kind': 'derived', 'owner': 'Sancion'},
 {'id': 'Apelacion.id_apelacion',
  'label': 'id_apelacion',
  'x': 1584,
  'y': 1516,
  'kind': 'key',
  'owner': 'Apelacion'},
 {'id': 'Apelacion.texto', 'label': 'texto', 'x': 1608, 'y': 1628, 'kind': 'simple', 'owner': 'Apelacion'},
 {'id': 'Apelacion.marca_lenguaje',
  'label': 'marca_lenguaje',
  'x': 1604,
  'y': 1736,
  'kind': 'simple',
  'owner': 'Apelacion'},
 {'id': 'Apelacion.fecha_apelacion',
  'label': 'fecha_apelacion',
  'x': 1568,
  'y': 1853,
  'kind': 'simple',
  'owner': 'Apelacion'},
 {'id': 'Apelacion.estado', 'label': 'estado', 'x': 1485, 'y': 1972, 'kind': 'simple', 'owner': 'Apelacion'},
 {'id': 'Apelacion.fecha_asignacion',
  'label': 'fecha_asignacion',
  'x': 1333,
  'y': 2074,
  'kind': 'simple',
  'owner': 'Apelacion'},
 {'id': 'Apelacion.nota_resolucion',
  'label': 'nota_resolucion',
  'x': 1107,
  'y': 2100,
  'kind': 'simple',
  'owner': 'Apelacion'},
 {'id': 'Apelacion.fecha_resolucion',
  'label': 'fecha_resolucion',
  'x': 910,
  'y': 2020,
  'kind': 'simple',
  'owner': 'Apelacion'},
 {'id': 'Reporte.id_reporte', 'label': 'id_reporte', 'x': 498, 'y': -871, 'kind': 'key', 'owner': 'Reporte'},
 {'id': 'Reporte.descripcion',
  'label': 'descripcion',
  'x': 391,
  'y': -988,
  'kind': 'simple',
  'owner': 'Reporte'},
 {'id': 'Reporte.fecha_reporte',
  'label': 'fecha_reporte',
  'x': 430,
  'y': -1094,
  'kind': 'simple',
  'owner': 'Reporte'},
 {'id': 'Reporte.estado', 'label': 'estado', 'x': 491, 'y': -1206, 'kind': 'simple', 'owner': 'Reporte'},
 {'id': 'Reporte.fecha_asignacion',
  'label': 'fecha_asignacion',
  'x': 578,
  'y': -1317,
  'kind': 'simple',
  'owner': 'Reporte'},
 {'id': 'Reporte.nota_resolucion',
  'label': 'nota_resolucion',
  'x': 705,
  'y': -1429,
  'kind': 'simple',
  'owner': 'Reporte'},
 {'id': 'Reporte.fecha_resolucion',
  'label': 'fecha_resolucion',
  'x': 937,
  'y': -1404,
  'kind': 'simple',
  'owner': 'Reporte'},
 {'id': 'BitacoraAcceso.id_bitacora',
  'label': 'id_bitacora',
  'x': -1234,
  'y': 1056,
  'kind': 'key',
  'owner': 'BitacoraAcceso'},
 {'id': 'BitacoraAcceso.identificador_capturado',
  'label': 'identificador_capturado',
  'x': -1427,
  'y': 950,
  'kind': 'simple',
  'owner': 'BitacoraAcceso'},
 {'id': 'BitacoraAcceso.resultado',
  'label': 'resultado',
  'x': -1525,
  'y': 814,
  'kind': 'simple',
  'owner': 'BitacoraAcceso'},
 {'id': 'BitacoraAcceso.direccion_ip',
  'label': 'direccion_ip',
  'x': -1560,
  'y': 696,
  'kind': 'simple',
  'owner': 'BitacoraAcceso'},
 {'id': 'BitacoraAcceso.fecha_hora',
  'label': 'fecha_hora',
  'x': -1563,
  'y': 589,
  'kind': 'simple',
  'owner': 'BitacoraAcceso'},
 {'id': 'BitacoraModeracion.id_bitacora',
  'label': 'id_bitacora',
  'x': -1562,
  'y': -537,
  'kind': 'key',
  'owner': 'BitacoraModeracion'},
 {'id': 'BitacoraModeracion.accion',
  'label': 'accion',
  'x': -1561,
  'y': -644,
  'kind': 'simple',
  'owner': 'BitacoraModeracion'},
 {'id': 'BitacoraModeracion.detalle',
  'label': 'detalle',
  'x': -1531,
  'y': -755,
  'kind': 'simple',
  'owner': 'BitacoraModeracion'},
 {'id': 'BitacoraModeracion.fecha_hora',
  'label': 'fecha_hora',
  'x': -1463,
  'y': -866,
  'kind': 'simple',
  'owner': 'BitacoraModeracion'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
