# -*- coding: utf-8 -*-
"""Modelo E-R «Partida», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion partida"""

ENTITIES = {'Partida': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Participacion': {'x': 1170, 'y': 0, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Jugada': {'x': 585, 'y': 945, 'w': 290, 'h': 110, 'kind': 'weak'},
 'OfertaTablas': {'x': 2070, 'y': -270, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Modo': {'x': -810, 'y': 585, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 1755, 'y': 765, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_Partida_Modo',
  'label': 'Se juega en',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Partida', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': -405,
  'y': 292},
 {'id': 'FK_Participacion_Partida',
  'label': 'Reúne',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', True, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': 585,
  'y': 0},
 {'id': 'FK_Participacion_Usuario',
  'label': 'Participa',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': 1462,
  'y': 382},
 {'id': 'FK_Jugada_Partida',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', False, True, None), ('Jugada', 'N', '1', True, False, None)],
  'x': 292,
  'y': 472},
 {'id': 'FK_Jugada_Participacion',
  'label': 'Hace',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Participacion', '1', '1', False, True, None), ('Jugada', 'N', '1', True, False, None)],
  'x': 878,
  'y': 472},
 {'id': 'FK_OfertaTablas_Participacion',
  'label': 'Ofrece',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('OfertaTablas', 'N', '1', True, False, None)],
  'x': 1620,
  'y': -135}]

ATTRS = [{'id': 'Participacion.orden_turno',
  'label': 'orden_turno',
  'x': 475,
  'y': -186,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.simbolo_peon',
  'label': 'simbolo_peon',
  'x': 382,
  'y': -318,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.casilla_actual',
  'label': 'casilla_actual',
  'x': 434,
  'y': -425,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.muros_restantes',
  'label': 'muros_restantes',
  'x': 509,
  'y': -535,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.reloj_restante',
  'label': 'reloj_restante',
  'x': 612,
  'y': -642,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.elo_inicial',
  'label': 'elo_inicial',
  'x': 821,
  'y': -630,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.elo_final',
  'label': 'elo_final',
  'x': 865,
  'y': -794,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.diferencia_elo',
  'label': 'diferencia_elo',
  'x': 1070,
  'y': -713,
  'kind': 'derived',
  'owner': 'Participacion'},
 {'id': 'Participacion.resultado',
  'label': 'resultado',
  'x': 1185,
  'y': -850,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.posicion',
  'label': 'posicion',
  'x': 1270,
  'y': -713,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.forma_termino',
  'label': 'forma_termino',
  'x': 1461,
  'y': -799,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.conectado',
  'label': 'conectado',
  'x': 1508,
  'y': -636,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.fecha_desconexion',
  'label': 'fecha_desconexion',
  'x': 1716,
  'y': -651,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.terminada',
  'label': 'terminada',
  'x': 1705,
  'y': -482,
  'kind': 'derived',
  'owner': 'Participacion'},
 {'id': 'Partida.id_partida', 'label': 'id_partida', 'x': -440, 'y': -12, 'kind': 'key', 'owner': 'Partida'},
 {'id': 'Partida.tipo', 'label': 'tipo', 'x': -556, 'y': -123, 'kind': 'simple', 'owner': 'Partida'},
 {'id': 'Partida.estado', 'label': 'estado', 'x': -519, 'y': -236, 'kind': 'simple', 'owner': 'Partida'},
 {'id': 'Partida.minutos_reloj',
  'label': 'minutos_reloj',
  'x': -452,
  'y': -347,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.fecha_inicio',
  'label': 'fecha_inicio',
  'x': -339,
  'y': -458,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.fecha_fin',
  'label': 'fecha_fin',
  'x': -147,
  'y': -415,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.forma_termino',
  'label': 'forma_termino',
  'x': -74,
  'y': -565,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.turno_actual',
  'label': 'turno_actual',
  'x': 42,
  'y': -438,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Jugada.numero_jugada',
  'label': 'numero_jugada',
  'x': 1020,
  'y': 876,
  'kind': 'key',
  'owner': 'Jugada'},
 {'id': 'Jugada.tipo', 'label': 'tipo', 'x': 1023, 'y': 983, 'kind': 'simple', 'owner': 'Jugada'},
 {'id': 'Jugada.casilla_origen',
  'label': 'casilla_origen',
  'x': 998,
  'y': 1096,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.casilla_destino',
  'label': 'casilla_destino',
  'x': 927,
  'y': 1222,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.surco', 'label': 'surco', 'x': 798, 'y': 1330, 'kind': 'simple', 'owner': 'Jugada'},
 {'id': 'Jugada.orientacion',
  'label': 'orientacion',
  'x': 631,
  'y': 1383,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.tiempo_consumido',
  'label': 'tiempo_consumido',
  'x': 427,
  'y': 1356,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.fecha_jugada',
  'label': 'fecha_jugada',
  'x': 268,
  'y': 1251,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'OfertaTablas.id_oferta',
  'label': 'id_oferta',
  'x': 2483,
  'y': -421,
  'kind': 'key',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.numero_jugada',
  'label': 'numero_jugada',
  'x': 2508,
  'y': -309,
  'kind': 'simple',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.fecha_oferta',
  'label': 'fecha_oferta',
  'x': 2505,
  'y': -202,
  'kind': 'simple',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.estado',
  'label': 'estado',
  'x': 2472,
  'y': -91,
  'kind': 'simple',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.fecha_respuesta',
  'label': 'fecha_respuesta',
  'x': 2392,
  'y': 30,
  'kind': 'simple',
  'owner': 'OfertaTablas'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
