# -*- coding: utf-8 -*-
"""Modelo E-R «Partida», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion partida"""

ENTITIES = {'Partida': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Participacion': {'x': 1690, 'y': 0, 'w': 290, 'h': 110, 'kind': 'weak'},
 'ParticipacionObjeto': {'x': 3055, 'y': 910, 'w': 356, 'h': 110, 'kind': 'weak'},
 'Jugada': {'x': 845, 'y': 1365, 'w': 290, 'h': 110, 'kind': 'weak'},
 'OfertaTablas': {'x': 3250, 'y': -325, 'w': 290, 'h': 110, 'kind': 'strong'},
 'EnlaceEspectador': {'x': 3120, 'y': 1885, 'w': 309, 'h': 110, 'kind': 'strong'},
 'Modo': {'x': -1170, 'y': 845, 'w': 290, 'h': 110, 'kind': 'strong'},
 'NivelIA': {'x': -260, 'y': 1495, 'w': 290, 'h': 110, 'kind': 'strong'},
 'ObjetoCosmetico': {'x': 4160, 'y': 910, 'w': 293, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 1950, 'y': 1495, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_Partida_Modo',
  'label': 'Se juega en',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Partida', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': -585,
  'y': 422},
 {'id': 'FK_Partida_NivelIA',
  'label': 'Enfrenta',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Partida', '1', 'N', False, False, None), ('NivelIA', '1', '1', False, True, None)],
  'x': -130,
  'y': 748},
 {'id': 'FK_Participacion_Partida',
  'label': 'Reúne',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', True, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': 845,
  'y': 0},
 {'id': 'FK_Participacion_Usuario',
  'label': 'Participa',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('Participacion', 'N', '1', True, False, None)],
  'x': 1820,
  'y': 748},
 {'id': 'FK_ParticipacionObjeto_Participacion',
  'label': 'Fija',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Participacion', '1', '1', True, True, None),
           ('ParticipacionObjeto', 'N', '1', True, False, None)],
  'x': 2372,
  'y': 455},
 {'id': 'FK_ParticipacionObjeto_ObjetoCosmetico',
  'label': 'Luce',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('ParticipacionObjeto', '1', 'N', True, False, None),
           ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': 3608,
  'y': 910},
 {'id': 'FK_Jugada_Partida',
  'label': 'Registra',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Partida', '1', '1', False, True, None), ('Jugada', 'N', '1', True, False, None)],
  'x': 422,
  'y': 682},
 {'id': 'FK_Jugada_Participacion',
  'label': 'Hace',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('Jugada', 'N', '1', False, False, None)],
  'x': 1268,
  'y': 682},
 {'id': 'FK_OfertaTablas_Participacion',
  'label': 'Ofrece',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('OfertaTablas', 'N', '1', True, False, None)],
  'x': 2470,
  'y': -162},
 {'id': 'FK_EnlaceEspectador_Participacion',
  'label': 'Comparte',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Participacion', '1', '1', False, True, None), ('EnlaceEspectador', 'N', '1', True, False, None)],
  'x': 2405,
  'y': 942}]

ATTRS = [{'id': 'Participacion.orden_turno',
  'label': 'orden_turno',
  'x': 1097,
  'y': -94,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.simbolo_peon',
  'label': 'simbolo_peon',
  'x': 988,
  'y': -201,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.casilla_actual',
  'label': 'casilla_actual',
  'x': 1028,
  'y': -309,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.muros_restantes',
  'label': 'muros_restantes',
  'x': 1092,
  'y': -419,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.reloj_restante',
  'label': 'reloj_restante',
  'x': 1183,
  'y': -525,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.elo_inicial',
  'label': 'elo_inicial',
  'x': 1325,
  'y': -632,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.elo_final',
  'label': 'elo_final',
  'x': 1515,
  'y': -574,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.diferencia_elo',
  'label': 'diferencia_elo',
  'x': 1588,
  'y': -723,
  'kind': 'derived',
  'owner': 'Participacion'},
 {'id': 'Participacion.resultado',
  'label': 'resultado',
  'x': 1700,
  'y': -600,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.posicion',
  'label': 'posicion',
  'x': 1817,
  'y': -719,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.forma_termino',
  'label': 'forma_termino',
  'x': 1895,
  'y': -564,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.conectado',
  'label': 'conectado',
  'x': 2088,
  'y': -612,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.fecha_desconexion',
  'label': 'fecha_desconexion',
  'x': 2114,
  'y': -424,
  'kind': 'simple',
  'owner': 'Participacion'},
 {'id': 'Participacion.terminada',
  'label': 'terminada',
  'x': 2199,
  'y': -318,
  'kind': 'derived',
  'owner': 'Participacion'},
 {'id': 'Partida.id_partida', 'label': 'id_partida', 'x': -434, 'y': 73, 'kind': 'key', 'owner': 'Partida'},
 {'id': 'Partida.tipo', 'label': 'tipo', 'x': -569, 'y': -35, 'kind': 'simple', 'owner': 'Partida'},
 {'id': 'Partida.estado', 'label': 'estado', 'x': -552, 'y': -143, 'kind': 'simple', 'owner': 'Partida'},
 {'id': 'Partida.minutos_reloj',
  'label': 'minutos_reloj',
  'x': -510,
  'y': -254,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.fecha_inicio',
  'label': 'fecha_inicio',
  'x': -440,
  'y': -363,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.fecha_fin',
  'label': 'fecha_fin',
  'x': -323,
  'y': -470,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.forma_termino',
  'label': 'forma_termino',
  'x': -132,
  'y': -420,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.turno_actual',
  'label': 'turno_actual',
  'x': -35,
  'y': -569,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.permite_deshacer',
  'label': 'permite_deshacer',
  'x': 88,
  'y': -431,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.permite_sugerencias',
  'label': 'permite_sugerencias',
  'x': 331,
  'y': -464,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.deshacer_usados',
  'label': 'deshacer_usados',
  'x': 340,
  'y': -280,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Partida.sugerencias_usadas',
  'label': 'sugerencias_usadas',
  'x': 407,
  'y': -168,
  'kind': 'simple',
  'owner': 'Partida'},
 {'id': 'Jugada.numero_jugada',
  'label': 'numero_jugada',
  'x': 1256,
  'y': 1207,
  'kind': 'key',
  'owner': 'Jugada'},
 {'id': 'Jugada.tipo', 'label': 'tipo', 'x': 1283, 'y': 1319, 'kind': 'simple', 'owner': 'Jugada'},
 {'id': 'Jugada.casilla_origen',
  'label': 'casilla_origen',
  'x': 1281,
  'y': 1426,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.casilla_destino',
  'label': 'casilla_destino',
  'x': 1247,
  'y': 1544,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.surco', 'label': 'surco', 'x': 1167, 'y': 1665, 'kind': 'simple', 'owner': 'Jugada'},
 {'id': 'Jugada.orientacion',
  'label': 'orientacion',
  'x': 1038,
  'y': 1760,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.tiempo_consumido',
  'label': 'tiempo_consumido',
  'x': 838,
  'y': 1805,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.fecha_jugada',
  'label': 'fecha_jugada',
  'x': 639,
  'y': 1754,
  'kind': 'simple',
  'owner': 'Jugada'},
 {'id': 'Jugada.deshecha', 'label': 'deshecha', 'x': 513, 'y': 1654, 'kind': 'simple', 'owner': 'Jugada'},
 {'id': 'OfertaTablas.id_oferta',
  'label': 'id_oferta',
  'x': 3562,
  'y': -635,
  'kind': 'key',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.numero_jugada',
  'label': 'numero_jugada',
  'x': 3646,
  'y': -517,
  'kind': 'simple',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.fecha_oferta',
  'label': 'fecha_oferta',
  'x': 3683,
  'y': -400,
  'kind': 'simple',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.estado',
  'label': 'estado',
  'x': 3689,
  'y': -293,
  'kind': 'simple',
  'owner': 'OfertaTablas'},
 {'id': 'OfertaTablas.fecha_respuesta',
  'label': 'fecha_respuesta',
  'x': 3666,
  'y': -181,
  'kind': 'simple',
  'owner': 'OfertaTablas'},
 {'id': 'EnlaceEspectador.id_enlace',
  'label': 'id_enlace',
  'x': 3522,
  'y': 2063,
  'kind': 'key',
  'owner': 'EnlaceEspectador'},
 {'id': 'EnlaceEspectador.token_hash',
  'label': 'token_hash',
  'x': 3448,
  'y': 2178,
  'kind': 'simple',
  'owner': 'EnlaceEspectador'},
 {'id': 'EnlaceEspectador.fecha_creacion',
  'label': 'fecha_creacion',
  'x': 3307,
  'y': 2283,
  'kind': 'simple',
  'owner': 'EnlaceEspectador'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
