# -*- coding: utf-8 -*-
"""Modelo E-R «Perfil y personalización», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion perfil"""

ENTITIES = {'HistorialNickname': {'x': -1020, 'y': -660, 'w': 325, 'h': 110, 'kind': 'weak'},
 'Avatar': {'x': -1020, 'y': 660, 'w': 290, 'h': 110, 'kind': 'strong'},
 'EnlaceRed': {'x': 0, 'y': -900, 'w': 290, 'h': 110, 'kind': 'strong'},
 'UsuarioObjeto': {'x': 1080, 'y': 0, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Equipamiento': {'x': 1620, 'y': 900, 'w': 290, 'h': 110, 'kind': 'weak'},
 'ObjetoCosmetico': {'x': 2160, 'y': 0, 'w': 293, 'h': 110, 'kind': 'strong'},
 'Ranura': {'x': 2700, 'y': 900, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_HistorialNickname_Usuario',
  'label': 'Cambia nombre',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('HistorialNickname', '1', '1', True, False, None)],
  'x': -510,
  'y': -330},
 {'id': 'FK_Avatar_Usuario',
  'label': 'Sube',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('Avatar', 'N', '1', True, False, None)],
  'x': -510,
  'y': 330},
 {'id': 'FK_EnlaceRed_Usuario',
  'label': 'Publica',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('EnlaceRed', 'N', '1', True, False, None)],
  'x': 0,
  'y': -450},
 {'id': 'FK_UsuarioObjeto_Usuario',
  'label': 'Posee',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', True, True, None), ('UsuarioObjeto', 'N', '1', True, False, None)],
  'x': 540,
  'y': 0},
 {'id': 'FK_UsuarioObjeto_ObjetoCosmetico',
  'label': 'Corresponde a',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('UsuarioObjeto', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': 1620,
  'y': 0},
 {'id': 'FK_Equipamiento_UsuarioObjeto',
  'label': 'Usa',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Equipamiento', '1', '1', True, False, None), ('UsuarioObjeto', '1', '1', False, True, None)],
  'x': 1350,
  'y': 450},
 {'id': 'FK_Equipamiento_ObjetoCosmetico',
  'label': 'Muestra',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('Equipamiento', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': 1890,
  'y': 450},
 {'id': 'FK_Equipamiento_Ranura',
  'label': 'Ocupa',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('Equipamiento', '1', 'N', True, False, None), ('Ranura', '1', '1', False, True, None)],
  'x': 2160,
  'y': 900}]

ATTRS = [{'id': 'Avatar.id_avatar', 'label': 'id_avatar', 'x': -1023, 'y': 1100, 'kind': 'key', 'owner': 'Avatar'},
 {'id': 'Avatar.ruta_imagen',
  'label': 'ruta_imagen',
  'x': -1202,
  'y': 1061,
  'kind': 'simple',
  'owner': 'Avatar'},
 {'id': 'Avatar.formato', 'label': 'formato', 'x': -1333, 'y': 969, 'kind': 'simple', 'owner': 'Avatar'},
 {'id': 'Avatar.tamano_bytes',
  'label': 'tamano_bytes',
  'x': -1417,
  'y': 850,
  'kind': 'simple',
  'owner': 'Avatar'},
 {'id': 'Avatar.fecha_subida',
  'label': 'fecha_subida',
  'x': -1454,
  'y': 733,
  'kind': 'simple',
  'owner': 'Avatar'},
 {'id': 'Avatar.vigente', 'label': 'vigente', 'x': -1459, 'y': 626, 'kind': 'simple', 'owner': 'Avatar'},
 {'id': 'EnlaceRed.id_enlace',
  'label': 'id_enlace',
  'x': -226,
  'y': -1277,
  'kind': 'key',
  'owner': 'EnlaceRed'},
 {'id': 'EnlaceRed.orden', 'label': 'orden', 'x': -61, 'y': -1336, 'kind': 'simple', 'owner': 'EnlaceRed'},
 {'id': 'EnlaceRed.url', 'label': 'url', 'x': 114, 'y': -1325, 'kind': 'simple', 'owner': 'EnlaceRed'},
 {'id': 'HistorialNickname.nickname_anterior',
  'label': 'nickname_anterior',
  'x': -1438,
  'y': -798,
  'kind': 'simple',
  'owner': 'HistorialNickname'},
 {'id': 'HistorialNickname.fecha_cambio',
  'label': 'fecha_cambio',
  'x': -1370,
  'y': -927,
  'kind': 'simple',
  'owner': 'HistorialNickname'},
 {'id': 'UsuarioObjeto.fecha_obtencion',
  'label': 'fecha_obtencion',
  'x': 923,
  'y': -411,
  'kind': 'simple',
  'owner': 'UsuarioObjeto'},
 {'id': 'UsuarioObjeto.origen',
  'label': 'origen',
  'x': 1119,
  'y': -438,
  'kind': 'simple',
  'owner': 'UsuarioObjeto'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
