# -*- coding: utf-8 -*-
"""Modelo E-R «Emparejamiento, salas y chat», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion salas"""

ENTITIES = {'ColaEmparejamiento': {'x': 0, 'y': -1320, 'w': 340, 'h': 110, 'kind': 'weak'},
 'Sala': {'x': 1560, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'SalaParticipante': {'x': 780, 'y': 660, 'w': 309, 'h': 110, 'kind': 'weak'},
 'Invitacion': {'x': 780, 'y': -720, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Mensaje': {'x': 780, 'y': 1500, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Modo': {'x': 1560, 'y': -1320, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Partida': {'x': 3120, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_ColaEmparejamiento_Usuario',
  'label': 'Espera en',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('ColaEmparejamiento', '1', '1', True, False, None)],
  'x': 0,
  'y': -660},
 {'id': 'FK_ColaEmparejamiento_Modo',
  'label': 'Busca',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('ColaEmparejamiento', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 780,
  'y': -1320},
 {'id': 'FK_Sala_Anfitrion',
  'label': 'Crea',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'anfitrión'), ('Sala', 'N', '1', True, False, None)],
  'x': 780,
  'y': 0},
 {'id': 'FK_Sala_Modo',
  'label': 'Usa',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Sala', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 1560,
  'y': -660},
 {'id': 'FK_Sala_Partida',
  'label': 'Inicia',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sala', '1', '1', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': 2340,
  'y': 0},
 {'id': 'FK_SalaParticipante_Sala',
  'label': 'Admite',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Sala', '1', '1', False, True, None), ('SalaParticipante', 'N', '1', True, False, None)],
  'x': 1170,
  'y': 330},
 {'id': 'FK_SalaParticipante_Usuario',
  'label': 'Ocupa',
  'ratio': '1:1',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('SalaParticipante', '1', '1', True, False, None)],
  'x': 390,
  'y': 330},
 {'id': 'FK_Invitacion_Sala',
  'label': 'Da acceso a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Invitacion', '1', 'N', True, False, None), ('Sala', '1', '1', False, True, None)],
  'x': 1170,
  'y': -360},
 {'id': 'FK_Invitacion_Emisor',
  'label': 'Envía',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'emisor'), ('Invitacion', 'N', '1', True, False, None)],
  'x': 492,
  'y': -250},
 {'id': 'FK_Invitacion_Destinatario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'destinatario'), ('Invitacion', 'N', '1', True, False, None)],
  'x': 288,
  'y': -470},
 {'id': 'FK_Mensaje_Autor',
  'label': 'Escribe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'autor'), ('Mensaje', 'N', '1', True, False, None)],
  'x': 390,
  'y': 750},
 {'id': 'FK_Mensaje_Partida',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': 1950,
  'y': 750},
 {'id': 'FK_Mensaje_Sala',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Sala', '1', '1', False, True, None)],
  'x': 1170,
  'y': 750}]

ATTRS = [{'id': 'Sala.id_sala', 'label': 'id_sala', 'x': 2106, 'y': 126, 'kind': 'key', 'owner': 'Sala'},
 {'id': 'Sala.codigo', 'label': 'codigo', 'x': 2204, 'y': 247, 'kind': 'simple', 'owner': 'Sala'},
 {'id': 'Sala.muros_por_jugador',
  'label': 'muros_por_jugador',
  'x': 2151,
  'y': 355,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Sala.minutos_reloj',
  'label': 'minutos_reloj',
  'x': 2073,
  'y': 462,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Sala.permite_espectadores',
  'label': 'permite_espectadores',
  'x': 1946,
  'y': 572,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Sala.estado', 'label': 'estado', 'x': 1724, 'y': 536, 'kind': 'simple', 'owner': 'Sala'},
 {'id': 'Sala.fecha_creacion',
  'label': 'fecha_creacion',
  'x': 1644,
  'y': 685,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Sala.fecha_ultima_actividad',
  'label': 'fecha_ultima_actividad',
  'x': 1482,
  'y': 555,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Invitacion.id_invitacion',
  'label': 'id_invitacion',
  'x': 487,
  'y': -1048,
  'kind': 'key',
  'owner': 'Invitacion'},
 {'id': 'Invitacion.fecha_invitacion',
  'label': 'fecha_invitacion',
  'x': 660,
  'y': -1143,
  'kind': 'simple',
  'owner': 'Invitacion'},
 {'id': 'Invitacion.fecha_expiracion',
  'label': 'fecha_expiracion',
  'x': 888,
  'y': -1147,
  'kind': 'simple',
  'owner': 'Invitacion'},
 {'id': 'Invitacion.estado',
  'label': 'estado',
  'x': 1058,
  'y': -1061,
  'kind': 'simple',
  'owner': 'Invitacion'},
 {'id': 'Mensaje.id_mensaje', 'label': 'id_mensaje', 'x': 988, 'y': 1888, 'kind': 'key', 'owner': 'Mensaje'},
 {'id': 'Mensaje.canal', 'label': 'canal', 'x': 819, 'y': 1938, 'kind': 'simple', 'owner': 'Mensaje'},
 {'id': 'Mensaje.texto', 'label': 'texto', 'x': 645, 'y': 1919, 'kind': 'simple', 'owner': 'Mensaje'},
 {'id': 'Mensaje.fecha_envio',
  'label': 'fecha_envio',
  'x': 498,
  'y': 1838,
  'kind': 'simple',
  'owner': 'Mensaje'},
 {'id': 'SalaParticipante.plaza',
  'label': 'plaza',
  'x': 619,
  'y': 251,
  'kind': 'simple',
  'owner': 'SalaParticipante'},
 {'id': 'SalaParticipante.listo',
  'label': 'listo',
  'x': 799,
  'y': 220,
  'kind': 'simple',
  'owner': 'SalaParticipante'},
 {'id': 'SalaParticipante.fecha_union',
  'label': 'fecha_union',
  'x': 989,
  'y': 130,
  'kind': 'simple',
  'owner': 'SalaParticipante'},
 {'id': 'ColaEmparejamiento.minutos_reloj',
  'label': 'minutos_reloj',
  'x': -396,
  'y': -1512,
  'kind': 'simple',
  'owner': 'ColaEmparejamiento'},
 {'id': 'ColaEmparejamiento.fecha_entrada',
  'label': 'fecha_entrada',
  'x': -306,
  'y': -1636,
  'kind': 'simple',
  'owner': 'ColaEmparejamiento'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
