# -*- coding: utf-8 -*-
"""Modelo E-R «Salas y chat», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion salas"""

ENTITIES = {'Sala': {'x': 1300, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Mensaje': {'x': 1300, 'y': 1000, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Modo': {'x': 1300, 'y': -1000, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Partida': {'x': 2600, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_Sala_Anfitrion',
  'label': 'Crea',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'anfitrión'), ('Sala', 'N', '1', True, False, None)],
  'x': 650,
  'y': 0},
 {'id': 'FK_Sala_Modo',
  'label': 'Usa',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Sala', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': 1300,
  'y': -500},
 {'id': 'FK_Sala_Partida',
  'label': 'Inicia',
  'ratio': '1:1',
  'kind': 'normal',
  'ends': [('Sala', '1', '1', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': 1950,
  'y': 0},
 {'id': 'FK_Mensaje_Autor',
  'label': 'Escribe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'autor'), ('Mensaje', 'N', '1', True, False, None)],
  'x': 650,
  'y': 500},
 {'id': 'FK_Mensaje_Partida',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Partida', '1', '1', False, True, None)],
  'x': 1950,
  'y': 500},
 {'id': 'FK_Mensaje_Sala',
  'label': 'Pertenece a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Mensaje', '1', 'N', False, False, None), ('Sala', '1', '1', False, True, None)],
  'x': 1300,
  'y': 500}]

ATTRS = [{'id': 'Sala.id_sala', 'label': 'id_sala', 'x': 1554, 'y': -759, 'kind': 'key', 'owner': 'Sala'},
 {'id': 'Sala.codigo', 'label': 'codigo', 'x': 1744, 'y': -817, 'kind': 'simple', 'owner': 'Sala'},
 {'id': 'Sala.muros_por_jugador',
  'label': 'muros_por_jugador',
  'x': 1787,
  'y': -635,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Sala.minutos_reloj',
  'label': 'minutos_reloj',
  'x': 2007,
  'y': -604,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Sala.estado', 'label': 'estado', 'x': 1967, 'y': -442, 'kind': 'simple', 'owner': 'Sala'},
 {'id': 'Sala.fecha_creacion',
  'label': 'fecha_creacion',
  'x': 2028,
  'y': -332,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Sala.fecha_ultima_actividad',
  'label': 'fecha_ultima_actividad',
  'x': 2071,
  'y': -214,
  'kind': 'simple',
  'owner': 'Sala'},
 {'id': 'Mensaje.id_mensaje', 'label': 'id_mensaje', 'x': 1599, 'y': 1323, 'kind': 'key', 'owner': 'Mensaje'},
 {'id': 'Mensaje.canal', 'label': 'canal', 'x': 1463, 'y': 1409, 'kind': 'simple', 'owner': 'Mensaje'},
 {'id': 'Mensaje.texto', 'label': 'texto', 'x': 1291, 'y': 1440, 'kind': 'simple', 'owner': 'Mensaje'},
 {'id': 'Mensaje.fecha_envio',
  'label': 'fecha_envio',
  'x': 1113,
  'y': 1398,
  'kind': 'simple',
  'owner': 'Mensaje'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
