# -*- coding: utf-8 -*-
"""Modelo E-R «Clasificación y economía», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion economia"""

ENTITIES = {'EstadisticaModo': {'x': -1300, 'y': 0, 'w': 293, 'h': 110, 'kind': 'weak'},
 'HistorialDivision': {'x': -1950, 'y': 950, 'w': 325, 'h': 110, 'kind': 'strong'},
 'Caja': {'x': 1250, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'CajaContenido': {'x': 2350, 'y': 0, 'w': 290, 'h': 110, 'kind': 'weak'},
 'MovimientoMoneda': {'x': 1000, 'y': 1100, 'w': 309, 'h': 110, 'kind': 'strong'},
 'Division': {'x': -2500, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Modo': {'x': -1300, 'y': -1100, 'w': 290, 'h': 110, 'kind': 'strong'},
 'ObjetoCosmetico': {'x': 2350, 'y': 1150, 'w': 293, 'h': 110, 'kind': 'strong'},
 'Partida': {'x': 0, 'y': 1500, 'w': 290, 'h': 110, 'kind': 'strong'},
 'TipoCaja': {'x': 1250, 'y': -1000, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_EstadisticaModo_Usuario',
  'label': 'Tiene',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', True, True, None), ('EstadisticaModo', 'N', '1', True, False, None)],
  'x': -650,
  'y': 0},
 {'id': 'FK_EstadisticaModo_Modo',
  'label': 'Mide',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('EstadisticaModo', '1', 'N', True, False, None), ('Modo', '1', '1', False, True, None)],
  'x': -1300,
  'y': -550},
 {'id': 'FK_EstadisticaModo_Division',
  'label': 'Ubica en',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('EstadisticaModo', '1', 'N', False, False, None), ('Division', '1', '1', False, True, None)],
  'x': -1900,
  'y': 0},
 {'id': 'FK_HistorialDivision_EstadisticaModo',
  'label': 'Acumula',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('EstadisticaModo', '1', '1', False, True, None),
           ('HistorialDivision', 'N', '1', True, False, None)],
  'x': -1625,
  'y': 475},
 {'id': 'FK_HistorialDivision_Anterior',
  'label': 'Sale de',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('HistorialDivision', '1', 'N', False, False, None),
           ('Division', '1', '1', False, True, 'anterior')],
  'x': -2070,
  'y': 443},
 {'id': 'FK_HistorialDivision_Nueva',
  'label': 'Llega a',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('HistorialDivision', '1', 'N', True, False, None), ('Division', '1', '1', False, True, 'nueva')],
  'x': -2355,
  'y': 550},
 {'id': 'FK_Caja_Usuario',
  'label': 'Obtiene',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('Caja', 'N', '1', True, False, None)],
  'x': 625,
  'y': 0},
 {'id': 'FK_Caja_TipoCaja',
  'label': 'Es de tipo',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('Caja', '1', 'N', True, False, None), ('TipoCaja', '1', '1', False, True, None)],
  'x': 1250,
  'y': -500},
 {'id': 'FK_CajaContenido_Caja',
  'label': 'Contiene',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Caja', '1', '1', False, True, None), ('CajaContenido', 'N', '1', True, False, None)],
  'x': 1800,
  'y': 0},
 {'id': 'FK_CajaContenido_ObjetoCosmetico',
  'label': 'Entrega',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('CajaContenido', '1', 'N', True, False, None), ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': 2350,
  'y': 575},
 {'id': 'FK_MovimientoMoneda_Usuario',
  'label': 'Mueve',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, None), ('MovimientoMoneda', 'N', '1', True, False, None)],
  'x': 500,
  'y': 550},
 {'id': 'FK_MovimientoMoneda_Partida',
  'label': 'Paga',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Partida', '1', '1', False, True, None), ('MovimientoMoneda', 'N', '1', False, False, None)],
  'x': 500,
  'y': 1300},
 {'id': 'FK_MovimientoMoneda_ObjetoCosmetico',
  'label': 'Paga',
  'ratio': 'N:1',
  'kind': 'normal',
  'ends': [('MovimientoMoneda', '1', 'N', False, False, None),
           ('ObjetoCosmetico', '1', '1', False, True, None)],
  'x': 1675,
  'y': 1125},
 {'id': 'FK_MovimientoMoneda_Caja',
  'label': 'Origina',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Caja', '1', '1', False, True, None), ('MovimientoMoneda', 'N', '1', False, False, None)],
  'x': 1125,
  'y': 550}]

ATTRS = [{'id': 'EstadisticaModo.puntos_elo',
  'label': 'puntos_elo',
  'x': -558,
  'y': 164,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.fecha_ultima_partida',
  'label': 'fecha_ultima_partida',
  'x': -456,
  'y': 282,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.elo_maximo',
  'label': 'elo_maximo',
  'x': -504,
  'y': 397,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.partidas_jugadas',
  'label': 'partidas_jugadas',
  'x': -567,
  'y': 504,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.partidas_ganadas',
  'label': 'partidas_ganadas',
  'x': -654,
  'y': 613,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.partidas_perdidas',
  'label': 'partidas_perdidas',
  'x': -783,
  'y': 725,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.racha_actual',
  'label': 'racha_actual',
  'x': -1009,
  'y': 702,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.mejor_racha',
  'label': 'mejor_racha',
  'x': -1077,
  'y': 862,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.tiempo_total_jugado',
  'label': 'tiempo_total_jugado',
  'x': -1307,
  'y': 760,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.barreras_colocadas',
  'label': 'barreras_colocadas',
  'x': -1462,
  'y': 875,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'EstadisticaModo.abandonos',
  'label': 'abandonos',
  'x': -1529,
  'y': 725,
  'kind': 'simple',
  'owner': 'EstadisticaModo'},
 {'id': 'Caja.id_caja', 'label': 'id_caja', 'x': 1790, 'y': 150, 'kind': 'key', 'owner': 'Caja'},
 {'id': 'Caja.origen', 'label': 'origen', 'x': 1883, 'y': 275, 'kind': 'simple', 'owner': 'Caja'},
 {'id': 'Caja.estado', 'label': 'estado', 'x': 1819, 'y': 391, 'kind': 'simple', 'owner': 'Caja'},
 {'id': 'Caja.fecha_obtencion',
  'label': 'fecha_obtencion',
  'x': 1725,
  'y': 501,
  'kind': 'simple',
  'owner': 'Caja'},
 {'id': 'Caja.fecha_apertura',
  'label': 'fecha_apertura',
  'x': 1509,
  'y': 497,
  'kind': 'simple',
  'owner': 'Caja'},
 {'id': 'Caja.fecha_caducidad',
  'label': 'fecha_caducidad',
  'x': 1434,
  'y': 665,
  'kind': 'simple',
  'owner': 'Caja'},
 {'id': 'MovimientoMoneda.id_movimiento',
  'label': 'id_movimiento',
  'x': 1381,
  'y': 1320,
  'kind': 'key',
  'owner': 'MovimientoMoneda'},
 {'id': 'MovimientoMoneda.tipo',
  'label': 'tipo',
  'x': 1283,
  'y': 1437,
  'kind': 'simple',
  'owner': 'MovimientoMoneda'},
 {'id': 'MovimientoMoneda.importe',
  'label': 'importe',
  'x': 1136,
  'y': 1518,
  'kind': 'simple',
  'owner': 'MovimientoMoneda'},
 {'id': 'MovimientoMoneda.fecha_movimiento',
  'label': 'fecha_movimiento',
  'x': 931,
  'y': 1535,
  'kind': 'simple',
  'owner': 'MovimientoMoneda'},
 {'id': 'CajaContenido.numero',
  'label': 'numero',
  'x': 2459,
  'y': -426,
  'kind': 'key',
  'owner': 'CajaContenido'},
 {'id': 'CajaContenido.monedas_conversion',
  'label': 'monedas_conversion',
  'x': 2635,
  'y': -335,
  'kind': 'simple',
  'owner': 'CajaContenido'},
 {'id': 'CajaContenido.convertido',
  'label': 'convertido',
  'x': 2736,
  'y': -211,
  'kind': 'derived',
  'owner': 'CajaContenido'},
 {'id': 'HistorialDivision.id_historial_division',
  'label': 'id_historial_division',
  'x': -1903,
  'y': 1387,
  'kind': 'key',
  'owner': 'HistorialDivision'},
 {'id': 'HistorialDivision.fecha_cambio',
  'label': 'fecha_cambio',
  'x': -2135,
  'y': 1349,
  'kind': 'simple',
  'owner': 'HistorialDivision'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
