# -*- coding: utf-8 -*-
"""Modelo E-R «Relaciones entre jugadores y tutorial», generado por er/generar.py a partir de
er/esquema.json y er/diagramas.py. Se puede retocar a mano y volver a dibujar
con: python er/generar.py --sin-disposicion social"""

ENTITIES = {'Amistad': {'x': -960, 'y': -690, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Solicitud': {'x': 960, 'y': -690, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Silencio': {'x': -960, 'y': 690, 'w': 290, 'h': 110, 'kind': 'weak'},
 'Bloqueo': {'x': 960, 'y': 690, 'w': 290, 'h': 110, 'kind': 'weak'},
 'ProgresoTutorial': {'x': 0, 'y': 900, 'w': 309, 'h': 110, 'kind': 'weak'},
 'Leccion': {'x': 0, 'y': 1740, 'w': 290, 'h': 110, 'kind': 'strong'},
 'Usuario': {'x': 0, 'y': 0, 'w': 290, 'h': 110, 'kind': 'strong'}}

ENTITY_LABEL = {}

RELATIONS = [{'id': 'FK_Amistad_UsuarioA',
  'label': 'Es amigo',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'menor'), ('Amistad', 'N', '1', True, False, None)],
  'x': -392,
  'y': -467},
 {'id': 'FK_Amistad_UsuarioB',
  'label': 'Es amigo',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'mayor'), ('Amistad', 'N', '1', True, False, None)],
  'x': -568,
  'y': -223},
 {'id': 'FK_Solicitud_Solicitante',
  'label': 'Envía',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'solicitante'), ('Solicitud', 'N', '1', True, False, None)],
  'x': 568,
  'y': -223},
 {'id': 'FK_Solicitud_Destinatario',
  'label': 'Recibe',
  'ratio': '1:N',
  'kind': 'normal',
  'ends': [('Usuario', '1', '1', False, True, 'destinatario'), ('Solicitud', 'N', '1', True, False, None)],
  'x': 392,
  'y': -467},
 {'id': 'FK_Silencio_Usuario',
  'label': 'Silencia',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'quien silencia'), ('Silencio', 'N', '1', True, False, None)],
  'x': -568,
  'y': 223},
 {'id': 'FK_Silencio_Silenciado',
  'label': 'Es silenciado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'silenciado'), ('Silencio', 'N', '1', True, False, None)],
  'x': -392,
  'y': 467},
 {'id': 'FK_Bloqueo_Bloqueador',
  'label': 'Bloquea',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueador'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 392,
  'y': 467},
 {'id': 'FK_Bloqueo_Bloqueado',
  'label': 'Es bloqueado',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, 'bloqueado'), ('Bloqueo', 'N', '1', True, False, None)],
  'x': 568,
  'y': 223},
 {'id': 'FK_ProgresoTutorial_Usuario',
  'label': 'Avanza',
  'ratio': '1:N',
  'kind': 'identifying',
  'ends': [('Usuario', '1', '1', False, True, None), ('ProgresoTutorial', 'N', '1', True, False, None)],
  'x': 0,
  'y': 450},
 {'id': 'FK_ProgresoTutorial_Leccion',
  'label': 'Cubre',
  'ratio': 'N:1',
  'kind': 'identifying',
  'ends': [('ProgresoTutorial', '1', 'N', True, False, None), ('Leccion', '1', '1', False, True, None)],
  'x': 0,
  'y': 1320}]

ATTRS = [{'id': 'ProgresoTutorial.paso_actual',
  'label': 'paso_actual',
  'x': 401,
  'y': 718,
  'kind': 'simple',
  'owner': 'ProgresoTutorial'},
 {'id': 'ProgresoTutorial.fecha_actualizacion',
  'label': 'fecha_actualizacion',
  'x': 435,
  'y': 835,
  'kind': 'simple',
  'owner': 'ProgresoTutorial'},
 {'id': 'ProgresoTutorial.fecha_completada',
  'label': 'fecha_completada',
  'x': 438,
  'y': 943,
  'kind': 'simple',
  'owner': 'ProgresoTutorial'},
 {'id': 'ProgresoTutorial.completada',
  'label': 'completada',
  'x': 412,
  'y': 1054,
  'kind': 'derived',
  'owner': 'ProgresoTutorial'},
 {'id': 'Solicitud.id_solicitud',
  'label': 'id_solicitud',
  'x': 1220,
  'y': -1045,
  'kind': 'key',
  'owner': 'Solicitud'},
 {'id': 'Solicitud.fecha_solicitud',
  'label': 'fecha_solicitud',
  'x': 1334,
  'y': -922,
  'kind': 'simple',
  'owner': 'Solicitud'},
 {'id': 'Amistad.fecha_amistad',
  'label': 'fecha_amistad',
  'x': -1343,
  'y': -907,
  'kind': 'simple',
  'owner': 'Amistad'},
 {'id': 'Silencio.fecha_silencio',
  'label': 'fecha_silencio',
  'x': -1277,
  'y': 996,
  'kind': 'simple',
  'owner': 'Silencio'},
 {'id': 'Bloqueo.fecha_bloqueo',
  'label': 'fecha_bloqueo',
  'x': 1399,
  'y': 717,
  'kind': 'simple',
  'owner': 'Bloqueo'}]

ATTR_BY_ID = {a["id"]: a for a in ATTRS}

NOTES = []
